import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { Container } from "@/components/layout/container";
import { H2 } from "@/components/ui/typography";
import { Button } from "@/components/ui/button";
import { getFeaturedProjectsWithWebsite } from "@/lib/supabase/project-content";

function ProjectCard({ project, index }: { project: { id: string; slug: string; title: string; short_description: string; problem: string; solution: string; category: string; technologies: string[]; website_url: string | null }; index: number }) {
  return <article className={`group relative flex flex-col border-t border-border/80 py-8 transition-colors hover:border-primary/45 md:p-8 md:first:pl-0 ${index === 0 ? "md:col-span-2" : ""}`}><div className="flex items-start justify-between gap-5"><div><p className="font-mono text-[10px] font-semibold tracking-[0.16em] text-primary">{String(index + 1).padStart(2, "0")} / {project.category || "PROJECT"}</p><h3 className="mt-4 max-w-2xl font-mono text-xl font-semibold leading-tight tracking-[-0.04em] text-foreground sm:text-2xl">{project.title}</h3></div><span className="font-mono text-xs text-muted-foreground/50">CASE STUDY</span></div><p className="mt-5 max-w-2xl text-sm leading-6 text-muted-foreground">{project.short_description || project.solution || project.problem}</p>{project.technologies.length > 0 && <p className="mt-5 font-mono text-[10px] tracking-[0.12em] text-muted-foreground">{project.technologies.join(" · ")}</p>}<div className="mt-7 flex flex-wrap items-center gap-5"><Link href={`/work/${project.slug}`} className="inline-flex items-center gap-2 text-sm font-medium text-primary">View project <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" /></Link>{project.website_url && <a href={project.website_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">Visit Website <ArrowUpRight className="h-3.5 w-3.5" /></a>}</div></article>;
}

export async function FeaturedWork() {
  const projects = await getFeaturedProjectsWithWebsite();
  return <section className="bg-surface-muted py-14 md:py-18 lg:py-20"><Container><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-[11px] font-semibold tracking-[0.16em] text-primary">PROOF OF WORK</p><H2 className="mt-3">Work I&apos;ve done</H2><p className="mt-3 max-w-lg text-sm leading-relaxed text-muted-foreground">Real automation and integration work. Each project started with a business problem, not a technology choice.</p></div><Button variant="ghost" size="sm" asChild><Link href="/work">All work <ArrowRight className="h-4 w-4" /></Link></Button></div><div className="mt-10">{projects.length === 0 ? <div className="border-y border-dashed border-border py-16 text-center"><p className="font-mono text-sm text-muted-foreground/60">Case studies coming soon</p></div> : <div className="grid gap-5 md:grid-cols-2">{projects.map((project, index) => <ProjectCard key={project.id} project={project} index={index} />)}</div>}</div></Container></section>;
}
